footer-links:
  email: wsy0227@stu.xjtu.edu.cn
  github: Wangmerlyn

gitalk:
  ClientID: e6aac5c7ea16629df083
  ClientSecret: 95f5a7bb48087309009565514f4561f152277ddd
  repo: Wangmerlyn.github.io
  owner: Wangmerlyn

google_analytics: G-M77HL5HQEX

url: https://wangmerlyn.github.io
theme: jekyll-theme-architect
title: Wangmerlyn's testing blog
description: A test blog website