
baseURL = "https://wangmerlyn.github.io/"
languageCode = "en-us"
theme = "paper"


[params]
    # show header social icons
    github = 'Wangmerlyn'       # github.com/YOUR_GITHUB_ID
    rss = true                      # show rss icon with link

    # show home page profile
    avatar = '954117092@qq.com'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Wang Merlyn'
    bio = 'Duuuuuuude'

    # misc
    disableHLJS = true              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon

[params.utterances] # https://utteranc.es/
owner = "Wangmerlyn" # Your GitHub ID
repo = "https://github.com/Wangmerlyn/Wangmerlyn.github.io" # The repo to store comments